export const ExpectedLifePartnerFields: string[] = [
  "user_id",
  "age",
  "color",
  "height",
  "educational_qualifications",
  "zilla",
  "marital_status",
  "occupation",
  "economical_condition",
  "expected_characteristics",
  "aqidah_madhab",
  "isDivorced_Widow",
  "isChild",
  "isMasna",
  "isStudent",
  "expected_income",
];
