export const GeneralInfoFields: string[] = [
	"user_id",
	"bio_type",
	"isMarriageDone",
	"date_of_birth",
	"height",
	"gender",
	"weight",
	"blood_group",
	"screen_color",
	"nationality",
	"marital_status",
	"views_count",
	"purchases_count",
	"isFbPosted",
	"isFeatured",
];
