export const FamilyStatusFields: string[] = [
  "user_id",
  "father_name",
  "father_occupation",
  "isFatherAlive",
  "mother_name",
  "isMotherAlive",
  "mother_occupation",
  "number_of_brothers",
  "brother_info",
  "number_of_sisters",
  "sister_info",
  "uncle_info",
  "family_eco_condition",
  "eco_condition_type",
  "family_deeni_info",
  "isPordaEnvironment",
];
